models/Players.php
<?php

namespace app\models;
use Yii;


class Players extends \yii\db\ActiveRecord
{
    public static function tableName()
    {
        return '{{%players}}';
    }

    public function rules()
    {
        return [
            [['name', 'surname'], 'required'],
            [['name', 'surname', 'position'], 'string'],
            [['command'], 'integer'],
            [['date'], 'safe'],
        ];
    }

    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'surname' => 'Surname',
            'date' => 'Date',
            'position' => 'Position',
            'command' => 'Command',
        ];
    }

    public static function newPlayer($x)
    {

        $link = new Players();

        $link->attributes = $x;
        $link->save();

        return true;
    }

    public static function ebitPlayer($id, $x)
    {

        $link = Players::findOne($id);

        $link->attributes = $x;
        $link->save();

        return true;
    }


    public static function getPlayerId($id)
    {
        intval($id);                           // Возвращает целое значение переменной

        $result = self::find()
            ->where(['id' => $id])
            ->one();

        return $result;
    }

    public static function getPlayers($idCommand)
    {
        $result = self::findAll([
            'command' => $idCommand,
        ]);


        return $result;
    }


     public static function deletePlayer($id)
     {
         $x = Players::getPlayerId($id);
         $x->delete();
         return true;
     }


//*******************************************************************************************************************

}

controllers/PlayerController.php
<?php

namespace app\controllers;

use app\models\Team;
use app\models\Players;
use app\models\User;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;

class PlayerController extends Controller
{
    public $enableCsrfValidation = false;

    public function actionPlayers($idCommand)
    {
        $result = Players::getPlayers($idCommand);
        $result1 = Team::getTeamId($idCommand);

        $url = Yii::$app->urlManager->createUrl('player/new');
        //return $this->render('players', ['posts'=>$result, 'posts1'=>$result1]);
        return $this->render('players.twig', ['posts'=>$result, 'posts1'=>$result1, 'url'=>$url]);
    }

    public function actionNew($id)
    {
        if (isset($_POST['ok'])){

            $name= $_POST['name'];
            $surname= $_POST['surname'];
            $date = $_POST['date'];
            $position = $_POST['position'];
            $x = [
                'name' => $name, 'surname' => $surname, 'date' => $date, 'position' => $position, 'command' => $id
            ];

            if (Players::newPlayer($x)) return $this->redirect('index.php?r=player%2Fplayers&idCommand='.$id);
        }

        $result = Team::getTeams();

        //return $this->render('formaPlayers', ['posts'=>$result]);
        return $this->render('formaPlayers.twig', ['posts'=>$result]);
    }


   public function actionEdit($id)
   {
       if (isset($_POST['ok'])){

           $name= $_POST['name'];
           $surname= $_POST['surname'];
           $date = $_POST['date'];
           $position = $_POST['position'];
           $val = Team::getTeams();
           $res = Players::getPlayerId($id);
           $command = $res['command'];

           if (isset($_POST['command'])){

               foreach($val as $com){
                   if ($_POST['command'] == $com['name']){
                       $command = $com['id'];
                   }
               }
               $x = [
                   'name' => $name, 'surname' => $surname, 'date' => $date, 'position' => $position, 'command' => $command
               ];
               if (Players::ebitPlayer($id, $x)) return $this->redirect('index.php?r=player%2Fplayers&idCommand='.$command);
           }else
               $x = [
                   'name' => $name, 'surname' => $surname, 'date' => $date, 'position' => $position, 'command' => $command
               ];
               if (Players::ebitPlayer($id, $x)) return $this->redirect('index.php?r=player%2Fplayers&idCommand='.$command);
       }
       $team = Team::getTeams();
       $result = Players::getPlayerId($id);

       //return $this->render('editPlayers', ['posts'=>$result, 'team'=>$team]);
       return $this->render('editPlayers.twig', ['posts'=>$result, 'team'=>$team]);
   }

    public function actionDel($id)
    {
        $res = Players::getPlayerId($id);
        $command = $res['command'];

        if (isset($_POST['x'])) {
            if (Players::deletePlayer($id))
                return $this->redirect('index.php?r=player%2Fplayers&idCommand='.$command);
        }

        $name = $res['name'];
        return $this->render('delPlayer.twig', ['posts'=>$name]);
    }

}

views/player/delPlayer.php
<?php

$this->title = 'видалити гравця';
/**
 * Created by PhpStorm.
 * User: shum
 * Date: 23.03.17
 * Time: 12:56
 */
?>
<div>
    <p style="font-size: 30px; color: #9c3328;">
    Ви дійсно хочете видалити гравця - <?=$posts?> ?
    </p>
</div>
<form action="" method="post">
    <input id="form-token" type="hidden" name="<?=Yii::$app->request->csrfParam?>"
           value="<?=Yii::$app->request->csrfToken?>"/>
    <input type="submit" name="x" value="Видалити">

</form>

views/player/editPlayers.php
<?php
//use yii\helpers\Html;
$this->title = 'редагувати гравця';
/**
 * Created by PhpStorm.
 * User: shum
 * Date: 15.03.17
 * Time: 11:08
 */
?>
<p><h2>Внесіть зміни</h2></p><br>

<form name="teamNew" action="" method="post">
    <lebel class="forma"> Імя гравця </lebel> <br>
    <input type="text" name="name" required value="<?php echo $posts['name']?>"> <br><br>

    <lebel class="forma"> Фамілія гравця </lebel> <br>
    <input type="text" name="surname" required value="<?php echo $posts['surname']?>"> <br><br>

    <lebel class="forma"> Дата народження гравця </lebel> <br>
    <input type="date" name="date" required value="<?php echo $posts['date']?>"> <br><br>

    <lebel class="forma"> Позиція на полі </lebel> <br>
    <input type="text" name="position" required value="<?php echo $posts['position']?>"> <br><br>

    <lebel class="forma"> Якщо команда не змінилася, нічого вибирати не потрібно </lebel> <br>
    <select name="command" >
        <option></option>
        <?php foreach($team as $x):?>
            <option><?php echo $x['name']?></option>
        <?php endforeach ?>
    </select><br><br>

    <input type="submit" class="" name="ok" value="Змінити"> <br>
</form>
<br><br>
<pre><p><h4>    <- на сторінку <a href="<?=Yii::$app->urlManager->createUrl('/')?>"> Команди </a> </h4></p></pre>

views/player/formaPlayers.php
<?php
//use yii\helpers\Html;
$this->title = 'створити гравця';
/**
 * Created by PhpStorm.
 * User: shum
 * Date: 15.03.17
 * Time: 11:08
 */
?>
<p><h2>Для створення нового гравця заповніть форму</h2></p><br><br>

<form name="teamNew" action="" method="post">
    <lebel class="forma"> Імя гравця </lebel> <br>
    <input type="text" name="name" placeholder="імя плиз" required value=""> <br><br>

    <lebel class="forma"> Фамілія гравця </lebel> <br>
    <input type="text" name="surname" placeholder="прізвище плиз" required value=""> <br><br>

    <lebel class="forma"> Дата народження гравця </lebel> <br>
    <input type="date" name="date" placeholder="дату плиз" required value=""> <br><br>

    <lebel class="forma"> Позиція на полі </lebel> <br>
    <input type="text" name="position" placeholder="позицію плиз" required value=""> <br><br>

    <lebel class="forma"> Команда гравця </lebel> <br>

    <select name="command" required>
        <?php foreach($posts as $x):?>
    <option><?php echo $x['name']?></option>
        <?php endforeach ?>
    </select><br><br>

    <input type="submit" class="butn" name="ok" value="Створити"> <br>
</form>
<br><br>
<pre><p><h4>    <- на сторінку <a href="<?=Yii::$app->urlManager->createUrl('/')?>"> Команди </a></h4></p></pre>

views/player/players.php
<?php

$this->title = 'Гравці';
/**
 * Created by PhpStorm.
 * User: shum
 * Date: 15.03.17
 * Time: 11:08
 */
?>
<button class="button" onclick="location.href='<?=Yii::$app->urlManager->createUrl('player/new')?>'"> Добавити гравця</button>
<p><h3>Команда - <?php echo $posts1['name']?></h3></p>
<div class="datagrid">
    <table>
        <thead>
        <tr><th>id</th><th>Імя</th><th>Прізвище</th><th>Дата народження</th><th>Позиція на полі</th><th>редагувати</th><th>видалити</th></tr>
        </thead>
        <tfoot>
        <tr><td colspan="7">
                <div id="paging">
                    <ul>
                        <li><a href="#"><span>Previous</span></a></li>
                        <li><a href="#" class="active"><span>1</span></a></li>
                        <li><a href="#"><span>2</span></a></li>
                        <li><a href="#"><span>3</span></a></li>
                        <li><a href="#"><span>4</span></a></li>
                        <li><a href="#"><span>5</span></a></li>
                        <li><a href="#"><span>Next</span></a></li>
                    </ul>
                </div>
        </tr>
        </tfoot>
        <tbody>
        <?php $num=1; foreach($posts as $x):?>
        <?php $num++; if ($num%2==0):?>
        <tr>
            <td><?php echo $x['id']?></td>
            <td><?php echo $x['name']?></td>
            <td><?php echo $x['surname']?></td>
            <td><?php echo $x['date']?></td>
            <td><?php echo $x['position']?></td>
            <td><a href="<?=Yii::$app->urlManager->createUrl(['player/edit', 'id' => $x['id']])?>">Редагувати</a></td>
            <td><a href="<?=Yii::$app->urlManager->createUrl(['player/del', 'id' => $x['id']])?>">Видалити</a></td>
        </tr>
        <?php else: ?>
        <tr class="alt">
            <td><?php echo $x['id']?></td>
            <td><?php echo $x['name']?></td>
            <td><?php echo $x['surname']?></td>
            <td><?php echo $x['date']?></td>
            <td><?php echo $x['position']?></td>
            <td><a href="<?=Yii::$app->urlManager->createUrl(['player/edit', 'id' => $x['id']])?>">Редагувати</a></td>
            <td><a href="<?=Yii::$app->urlManager->createUrl(['player/del', 'id' => $x['id']])?>">Видалити</a></td>
        </tr>
            <?php endif;?>
        <?php endforeach ?>
        </tbody>
    </table>
</div>

<br><br>
<p><h4><- на сторінку <a href="<?=Yii::$app->urlManager->createUrl('/')?>"> Команди </a> </h4></p>